//registerUserAPI | API-1 | POST
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "tejdogip33",
  "password": "raviteja",
  "name": "Ravi Teja",
  "gender": "male"
}
###

//loginUserAPI | API-2 | POST
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###